// NOTE: The emojis are kept in their own file since apparently they can mess up the test coverage analysis (see https://github.com/denoland/deno/issues/10936).
export default {
  scroll: "📜",
  megaphone: "📣",
  surf: "🏄",
  questionMark: "❓",
  alert: "🚨",
  tools: "🛠️ ",
  info: "ℹ️ ",
  crossMark: "❌",
  bell: "🔔",
  globeWithMeridians: "🌐",
  checkMarkButton: "✅",
  greenSquare: "🟩",
  orangeSquare: "🟧",
  yellowSquare: "🟨",
  blueSquare: "🟦",
  redSquare: "🟥",
  purpleSquare: "🟪",
  brownSquare: "🟫",
  zzz: "💤",
};
